const booksData = [
  {
    title: "Pride and Prejudice",
    price: 47.5,
    publication_date: "1/14/2024",
    GenreId: 3,
    AuthorId: 1,
  },
  {
    title: "Animal Farm",
    price: 40,
    publication_date: "11/17/2023",
    GenreId: 4,
    AuthorId: 2,
  },
  {
    title: "Harry Potter and the Goblet of Fire",
    price: 40.75,
    publication_date: "12/1/2023",
    GenreId: 5,
    AuthorId: 3,
  },
  {
    title: "The Adventures of Tom Sawyer",
    price: 20.15,
    publication_date: "3/21/2024",
    GenreId: 6,
    AuthorId: 4,
  },
  {
    title: "One Hundred Years of Solitude",
    price: 99,
    publication_date: "7/29/2023",
    GenreId: 10,
    AuthorId: 5,
  },
  {
    title: "Song of Solomon",
    price: 75,
    publication_date: "1/22/2024",
    GenreId: 1,
    AuthorId: 6,
  },
  {
    title: "The Guide",
    price: 35,
    publication_date: "11/3/2023",
    GenreId: 2,
    AuthorId: 7,
  },
  {
    title: "A Farewell to Arms",
    price: 24,
    publication_date: "12/12/2023",
    GenreId: 8,
    AuthorId: 8,
  },
  {
    title: "To the Lighthouse.",
    price: 24,
    publication_date: "12/12/2023",
    GenreId: 9,
    AuthorId: 9,
  },
  {
    title: "Swami and Friends",
    price: 24,
    publication_date: "12/12/2023",
    GenreId: 10,
    AuthorId: 10,
  },
];
module.exports = booksData;
